apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
  namespace: lldap
type: Opaque
stringData:
  LLDAP_JWT_SECRET: "REPLACE_WITH_RANDOM"
  LLDAP_KEY_SEED: "REPLACE_WITH_RANDOM"
  LLDAP_LDAP_USER_DN: admin
  LLDAP_LDAP_USER_PASS: "Lldap!123"
  LLDAP_DATABASE_URL: postgres://lldap:lldap@postgres.rdbms.svc.cluster.local:5432/lldap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lldap-config
  namespace: lldap
data:
  LLDAP_HTTP_URL: http://localhost:17170
  LLDAP_LDAP_BASE_DN: dc=example,dc=com

---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: lldap-pvc
#   namespace: lldap
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  template:
    metadata:
      labels:
        app: lldap
    spec:
      containers:
      - name: lldap
        image: lldap/lldap:2026-05-26
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3890
          name: ldap
        - containerPort: 17170
          name: web
        envFrom:
          - configMapRef:
              name: lldap-config
          - secretRef:
              name: lldap-secret
        # volumeMounts:
        # - name: data
        #   mountPath: /data
        readinessProbe:
          httpGet:
            path: /health
            port: 17170
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 17170
          initialDelaySeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: "1"
            memory: 512Mi
      # volumes:
      # - name: data
      #   persistentVolumeClaim:
      #     claimName: lldap-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: lldap
spec:
  selector:
    app: lldap
  ports:
  - name: ldap
    port: 389
    targetPort: 3890
  - name: web
    port: 17170
    targetPort: 17170