---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
  namespace: lldap
type: Opaque
stringData:
  LLDAP_JWT_SECRET: "REPLACE_WITH_RANDOM"
  LLDAP_KEY_SEED: "REPLACE_WITH_RANDOM"
  LLDAP_LDAP_USER_DN: admin
  LLDAP_LDAP_USER_PASS: "Lldap!123"
  LLDAP_DATABASE_URL: postgres://lldap:lldap@postgres-metadata.rdbms.svc.cluster.local:5432/lldap