apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: airflow
type: Opaque
stringData:
  FERNET_KEY: "REPLACE_ME"
  AIRFLOW_ADMIN_USERNAME: "admin"
  AIRFLOW_ADMIN_PASSWORD: "admin"
  AIRFLOW_ADMIN_FIRSTNAME: "Admin"
  AIRFLOW_ADMIN_LASTNAME: "User"
  AIRFLOW_ADMIN_EMAIL: "admin@example.com"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  AIRFLOW_CONN_MINIO: "aws://minioadmin:minioadmin@?endpoint_url=http://minio.minio.svc.cluster.local:9000&region_name=us-east-1"