FROM apache/ranger-base:20251023-1-11

ARG RANGER_VERSION=2.8.0

ENV RANGER_HOME=/usr/lib/ranger/ranger--usersync

RUN mkdir -p ${RANGER_HOME}

RUN curl -fSL https://downloads.apache.org/ranger/${RANGER_VERSION}/services/usersync/ranger-${RANGER_VERSION}-usersync.tar.gz -o /tmp/ranger-usersync.tar.gz

RUN tar -xzf /tmp/ranger-usersync.tar.gz --strip-components=1 -C ${RANGER_HOME} && \
    rm -f /tmp/ranger-usersync.tar.gz

