---
apiVersion: v1
kind: Namespace
metadata:
  name: rdbms

---
apiVersion: v1
kind: Namespace
metadata:
  name: minio

---
apiVersion: v1
kind: Namespace
metadata:
  name: opensearch

---
apiVersion: v1
kind: Namespace
metadata:
  name: openldap

---
apiVersion: v1
kind: Namespace
metadata:
  name: ranger

---
apiVersion: v1
kind: Namespace
metadata:
  name: hive

---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow

---
apiVersion: v1
kind: Namespace
metadata:
  name: spark