apiVersion: v1
kind: Namespace
metadata:
  name: airflow

---
apiVersion: v1
kind: Namespace
metadata:
  name: rdbms

---
apiVersion: v1
kind: Namespace
metadata:
  name: minio

---
apiVersion: v1
kind: Namespace
metadata:
  name: spark

---
apiVersion: v1
kind: Namespace
metadata:
  name: ranger

---
apiVersion: v1
kind: Namespace
metadata:
  name: lldap

---
apiVersion: v1
kind: Namespace
metadata:
  name: opensearch