---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config-common
  # labels:
  #   app.kubernetes.io/name: opensearch
  #   app.kubernetes.io/part-of: opensearch-cluster
  namespace: opensearch
data:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    discovery.seed_hosts:
    - opensearch-cluster-master-headless
    cluster.initial_cluster_manager_nodes:
    - opensearch-cluster-master-0