apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config-worker
  namespace: airflow
data:
  AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
  AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: minio
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: s3://airflow-logs
  AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-worker-pod-template
  namespace: airflow
data:
  pod_template_file.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        component: airflow-worker
    spec:
      serviceAccountName: airflow
      restartPolicy: Never
      containers:
        - name: base
          image: apache/airflow:3.2.2-python3.14-fab-s3
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: airflow-config-common
            - configMapRef:
                name: airflow-config-worker
            - secretRef:
                name: airflow-secret
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.3.0
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/willyyeremi22/airflow-dag.git"
            - name: GIT_SYNC_BRANCH
              value: "prod"
            - name: GIT_SYNC_ROOT
              value: "/opt/airflow"
            - name: GIT_SYNC_DEST
              value: "dags"
            - name: GIT_SYNC_PERIOD
              value: "60s"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow 
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: dags
          emptyDir: {}
