apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config-common
  namespace: airflow
data:
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-metadata.rdbms.svc.cluster.local:5432/airflow
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__API__BASE_URL: http://localhost:8080
  AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE: airflow
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS: "True"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS_ON_FAILURE: "False"
  AIRFLOW__LOGGING__DELETE_LOCAL_LOGS: "False"
  AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
  AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: minio
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: s3://airflow-logs

