

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-worker-pod-template-1
  namespace: airflow
data:
  airflow_worker.yaml: |
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: airflow-config-worker
      namespace: airflow
    data:
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags

    ---
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        component: airflow-worker
    spec:
      serviceAccountName: airflow
      restartPolicy: Never
      containers:
        - name: airflow-worker
          image: apache/airflow:3.2.2-python3.14-s3-k8s
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: airflow-config-common
            - configMapRef:
                name: airflow-config-worker
            - secretRef:
                name: airflow-secret
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
              subPath: dags
              readOnly: true
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags
