# setup kubernetess on docker dekstop membolehkan banyak pod akses 1 pvc dengan accessModes ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitsync-config
  namespace: airflow
data:
  GITSYNC_REPO: "https://github.com/willyyeremi22/airflow-dag.git"
  GITSYNC_REF: "prod"
  GITSYNC_ROOT: "/opt/airflow"
  GITSYNC_LINK: "dags"
  GITSYNC_PERIOD: "15s"
  GITSYNC_ONE_TIME: "false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitsync
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitsync
  template:
    metadata:
      labels:
        app: gitsync
    spec:
      containers:
        - name: gitsync
          image: registry.k8s.io/git-sync/git-sync:v4.3.0
          envFrom:
            - configMapRef:
                name: gitsync-config
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags