apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: minio
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/minio:RELEASE.2025-09-07T16-13-09Z
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: minio-secret
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e

              until mc alias set local http://minio.minio.svc.cluster.local:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
                echo "waiting for minio..."
                sleep 3
              done

              mc mb --ignore-existing local/lakehouse
              mc mb --ignore-existing local/airflow-logs

