---
apiVersion: v1
kind: Secret
metadata:
  name: ranger-secret-admin
  namespace: ranger
type: Opaque
stringData:
  db_root_user: postgres
  db_root_password: postgres
  db_host: postgres-metadata.rdbms.svc.cluster.local:5432
  db_name: ranger
  db_user: ranger
  db_password: ranger
  rangerAdmin_password: Ranger!123
  rangerUsersync_password: Ranger!123
  rangerTagsync_password: Ranger!123
  keyadmin_password: Ranger!123
  xa_ldap_bind_password: password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ranger-config-admin
  namespace: ranger
data:
  DB_FLAVOR: POSTGRES
  policymgr_external_url: http://ranger-admin.ranger.svc.cluster.local:6080
  audit_store: elasticsearch
  audit_elasticsearch_urls: opensearch-coordinator.opensearch.svc.cluster.local
  audit_elasticsearch_port: "9200"
  audit_elasticsearch_protocol: http
  audit_elasticsearch_user: ""
  audit_elasticsearch_password: ""
  audit_elasticsearch_index: ranger_audit_logs
  audit_elasticsearch_bootstrap_enabled: "false"
  authServiceHostName: ranger-usersync.ranger.svc.cluster.local
  authServicePort: "5151"
  authentication_method: LDAP
  xa_ldap_url: ldap://lldap.lldap.svc.cluster.local:3890
  xa_ldap_userDNpattern: uid={0},ou=people,dc=example,dc=com
  xa_ldap_groupSearchBase: ou=groups,dc=example,dc=com
  xa_ldap_groupSearchFilter: (member={0})
  xa_ldap_groupRoleAttribute: cn
  xa_ldap_base_dn: dc=example,dc=com
  xa_ldap_bind_dn: uid=ranger_service,ou=people,dc=example,dc=com
  xa_ldap_userSearchFilter: (uid={0})
  xa_ldap_referral: ignore

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranger-admin
  namespace: ranger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranger-admin
  template:
    metadata:
      labels:
        app: ranger-admin
    spec:
      containers:
      - name: ranger-admin
        image: apache/ranger-custom-admin:2.8.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: ranger-config-admin
          - secretRef:
              name: ranger-secret-admin
        ports:
        - name: http
          containerPort: 6080

---
apiVersion: v1
kind: Service
metadata:
  name: ranger-admin
  namespace: ranger
spec:
  type: ClusterIP
  selector:
    app: ranger-admin
  ports:
    - name: http
      port: 6080
      targetPort: 6080
