apiVersion: v1
kind: Secret
metadata:
  name: ranger-secret
  namespace: ranger
type: Opaque
stringData:
  db_root_user: postgres
  db_root_password: postgres
  db_host: postgres.rdbms.svc.cluster.local:5432
  db_name: ranger
  db_user: ranger
  db_password: ranger

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ranger-config-admin
  namespace: ranger
data:
  DB_FLAVOR: POSTGRES

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranger-admin
  namespace: ranger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranger-admin
  template:
    metadata:
      labels:
        app: ranger-admin
    spec:
      containers:
      - name: ranger-admin
        image: apache/ranger-custom-admin:2.8.0
        envFrom:
          - configMapRef:
              name: ranger-config-admin
          - secretRef:
              name: ranger-secret
        command:
        - /bin/bash
        - -c
        - |
            echo "=== /opt/ranger ==="
            find /opt/ranger -maxdepth 2 -type d

            echo "=== scripts ==="
            ls -lah /home/ranger/scripts

            sleep 3600
        ports:
        - containerPort: 6080
        volumeMounts:
        - name: ranger-data
          mountPath: /opt/ranger
      volumes:
      - name: ranger-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: ranger-admin
  namespace: ranger
spec:
  selector:
    app: ranger-admin
  ports:
    - name: http
      port: 6080
      targetPort: 6080